return {
	descriptions = {
		Joker = {
			j_broken = {
				name = "ERREUR",
				text = {
					"Cette carte ne marche pas ou",
					"pas encore dans la version",
					"actuelle de ce mod.",
				},
			},
		},
		Blind = {
			bl_pvp = {
				name = "Votre adversaire",
				text = {
					"Jouez contre un autre joueur,",
					"celui avec le meilleur score gagne",
				},
			},
		},
	},
	misc = {
		challenge_names = {
			c_multiplayer_1 = "Multijoueur",
		},
		dictionary = {
			singleplayer = "Solo",
			join_lobby = "Rejoindre un Lobby",
			return_lobby = "Retour au Lobby",
			reconnect = "Reconnecter",
			create_lobby = "Créer un Lobby",
			start_lobby = "Démarrer le Lobby",
			enemy_score = "Score ennemi",
			enemy_hands = "Mains ennemies : ",
			coming_soon = "Prochainement!",
			ready = "Prêt",
			unready = "Pas prêt",
			wait_enemy = "En attente de l'ennemi...",
			lives = "Vies",
			leave_lobby = "Quitter le Lobby",
			lost_life = "Vie perdu",
			failed = "Échoué",
			defeat_enemy = "Ennemi vaincu",
			total_lives_lost = " Vies perdues ($4 chacune)",
			attrition_name = "Attrition",
			attrition_desc = "Chaque manche de boss est une compétition entre joueurs ou le joueur avec le score le plus bas perd une vie.",
			draft_name = "Plan",
			draft_desc = "Chaque joueur joue 3 manches normales, puis joue une mise ou chaque manche le joueur avec le meilleur score gagne.",
			royale_name = "Battle Royale",
			royale_desc = "Attrition, mais jusqu'à 8 joueurs et chaque joueur n'a qu'une seule vie.",
			vanilla_plus_name = "Vanilla+",
			vp_desc = "Le premier à échouer une manche perd la partie, pas de mises JcJ.",
			enter_lobby_code = "Entrez le Code Lobby",
			join_clip = "Coller depuis presse-papiers",
			username = "Nom : ",
			enter_username = "Entrez nom d'utilisateur",
			join_discord = "Rejoindre le ",
			discord_name = "Serveur Discord Balatro Multijoueur",
			discord_msg = "Vous pouvez signaler des bugs ou trouver des adversaires (English)",
			enter_to_save = "Appuyez sur entrée pour sauvegarder",
			in_lobby = "Dans le lobby",
			connected = "Connecté au Service",
			warn_service = "ATTENTION: Service Multijoueur manquant",
			set_name = "Définissez votre nom d'utilisateur dans le menu principal! (Mods > Multiplayer > Config)",
			start = "DÉMARRER",
			wait_for = "EN ATTENTE DE",
			host_start = "L'HÔTE POUR DÉMARRER",
			players = "JOUEURS",
			lobby_options_cap = "OPTIONS DU LOBBY",
			lobby_options = "Options du Lobby",
			copy_clipboard = "Copier dans le presse-papiers",
			connect_player = "Joueurs connectés : ",
			view_code = "VOIR LE CODE",
			leave = "QUITTER",
			opts_only_host = "Seul l'hôte peut changer ces options",
			opts_cb_money = "Donne $ quand perte de vie",
			opts_no_gold_on_loss = "Pas de récompense de mise si manche perdue",
			opts_death_on_loss = "Perte de vie en manche non-JcJ échouée",
			opts_start_antes = "Mises de départ",
			opts_diff_seeds = "Les joueurs ont des seeds différentes",
			opts_lives = "Vies",
			opts_gm = "Modificateurs de mode de jeu",
			bl_or = "ou",
			bl_life = "Vie",
			bl_death = "Mort",
			lobby = "Lobby",
			return_to = "Retour vers",
			enemy_loc_1 = "Ennemi",
			enemy_loc_2 = "lieu",
			loc_ready = "Prêt pour JcJ",
			loc_selecting = "Sélectionne une Mise",
			loc_shop = "Magasin",
			loc_playing = "En jeu ",
			current_seed = "Seed actuelle : ",
			random = "Aléatoire",
			reset = "Réinitialiser",
			set_custom_seed = "Personaliser Seed",
			mod_hash_warning = "Des joueurs ont des mods ou des versions de mods différentes! Cela peut causer des problèmes!",
		},
	},
}
